[project]
name = "gemini-ai-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.1.0",
    "fastmcp>=2.12.3",
    "requests>=2.32.5",
]
